LOGISTIC REGRESSION

In [3]:
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [45]:
sentiment_data = pd.read_csv('sentiment_dataset.csv')
sentiment_data.head(20)
data = sentiment_data.sample(frac=1).reset_index(drop=True)
data.head(5)

                              text     label
0  The instructions were confusing  negative
1           The shoes hurt my feet  negative
2      The traffic was a nightmare  negative
3        The service was unhelpful  negative
4         The website is confusing  negative

In [47]:
x = data['text']
y = data['label']

count_vec = CountVectorizer()
count_fit = count_vec.fit_transform(x)
count_array = count_fit.toarray()
bow = pd.DataFrame(count_array, columns=count_vec.get_feature_names_out())
bow

    again  am  amazing  and  app  ...  wonderfully  worked  working  workout  works
0       0   0        0    0    0  ...            0       0        0        0      0
1       0   0        0    0    0  ...            0       0        0        0      0
2       0   0        0    0    0  ...            0       0        0        0      0
3       0   0        0    0    0  ...            0       0        0        0      0
4       0   0        0    0    0  ...            0       0        0        0      0
..    ...  ..      ...  ...  ...  ...          ...     ...      ...      ...    ...
95      0   0        0    0    0  ...            0       0        0        0      1
96      0   0        0    0    0  ...            0       0        0        0      0
97      0   0        1    0    0  ...            0       0        0        0      0
98      0   0        0    0    0  ...            0       0        0        0      0
99      0   0        0    0    0  ...            0       0        0        0      0

[100 rows x 180 columns]

SPLIT DATA TO TRAINING AND TESTING SETS

In [48]:
x_train, x_test, y_train, y_test = train_test_split(bow, y, test_size=0.3, random_state=42)

In [49]:
lr = LogisticRegression(random_state=7).fit(x_train, y_train)

In [51]:
y_pred = lr.predict(x_test)
accuracy_score(y_pred, y_test)
print(classification_report(y_pred, y_test, zero_division=0))

              precision    recall  f1-score   support

    negative       1.00      0.62      0.77        24
    positive       0.40      1.00      0.57         6

    accuracy                           0.70        30
   macro avg       0.70      0.81      0.67        30
weighted avg       0.88      0.70      0.73        30

NAIVE BAYES

In [52]:
from sklearn.naive_bayes import MultinomialNB

In [53]:
nb = MultinomialNB()
nb.fit(x_train, y_train)
y_pred_nb = nb.predict(x_test)
accuracy_score(y_pred_nb, y_test)

0.7333333333333333

LINEAR SUPPORT VECTOR MACHINES

In [55]:
from sklearn.linear_model import SGDClassifier

In [61]:
svm = SGDClassifier()
svm.fit(x_train, y_train)
svm_y_pred = svm.predict(x_test)
accuracy_score(svm_y_pred, y_test)

0.5333333333333333